### ISSUE TITLE
When set sound on OFF and restart game the sound is again ON

### ISSUE THREAD

**Issue by ghost** [esviji/esviji-ubuntu-touch#3] opened 2020-05-12 18:01 UTC
When set sound on OFF and restart game the sound is again ON

**Comment by cibersheep** [comment] 2020-05-12 18:33
I can confirm this. In both version (the [unreleased](https://github.com/esviji/esviji-ubuntu-touch/commit/12930e61f690b3c544e5f0bcef9596560f973419)) and the current.

But if's remembered from play.esviji.com from Morph

**Comment by nhoizey** [comment] 2020-05-12 20:32
esviji uses localStorage in the browser to store the sound preference.

With the issue in #4, it looks like localStorage doesn't work here.

**Comment by cibersheep** [comment] 2020-05-12 20:56
This is the first thing I want to check, because the build works on Firefox on Desktop... I thought is was on by default... there's a way of forcing it... testing...

**Comment by nhoizey** [comment] 2020-05-12 21:17
If there is an issue with localStorage, IndexedDB might be a solution.

A migration is planned, but it was not for short term… 😅
https://github.com/esviji/esviji/issues/71

**Comment by cibersheep** [comment] 2020-05-13 00:55
Pushed a new version, I used a webview which uses LocalStorage properly :)
Fixed in https://github.com/esviji/esviji-ubuntu-touch/commit/b054d3f384538f65a6fad1cde98f3e11b7ee9aca

**Closed as completed by cibersheep** 2020-05-13 00:55 UTC
